# GlassKey Viewer Alpha
Notebook-first forward pass viewer.

Scope: **bytes → words → schedule → rounds → feed-forward**.

No reverse pass. No fake derived morphology. Real SHA-256 forward trace only.

In [1]:
import sys
sys.path.append('/mnt/data')
import glasskey_viewer_alpha as gk

In [2]:
trace_abc, trace_gk = gk.run_alpha()

GlassKey Viewer Alpha — notebook-first forward pass orbit
Scope: bytes -> words -> schedule -> rounds -> feed-forward

## GlassKey Viewer Alpha — abc

         field                                              value
0  message_len                                                  3
1   padded_len                                                 64
2       blocks                                                  1
3       rounds                                                 64
4       digest  ba7816bf8f01cfea414140de5dae2223b00361a396177a...

### Byte stream

    byte_index  block  offset  word  lane byte_hex ascii source
0            0      0       0     0     0     0x61     a    MSG
1            1      0       1     0     1     0x62     b    MSG
2            2      0       2     0     2     0x63     c    MSG
3            3      0       3     0     3     0x80     ·  PAD80
4            4      0       4     1     0     0x00     ·    PAD
5            5      0       5     1     1     0x00     ·    PAD
6            6      0       6     1     2     0x00     ·    PAD
7            7      0       7     1     3     0x00     ·    PAD
8            8      0       8     2     0     0x00     ·    PAD
9            9      0       9     2     1     0x00     ·    PAD
10          10      0      10     2     2     0x00     ·    PAD
11          11      0      11     2     3     0x00     ·    PAD
12          12      0      12     3     0     0x00     ·    PAD
13          13      0      13     3     1     0x00     ·    PAD
14          14      0      14     3     2     0x00     ·    PAD
15          15      0      15     3     3     0x00     ·    PAD
16          16      0      16     4     0     0x00     ·    PAD
17          17      0      17     4     1     0x00     ·    PAD
18          18      0      18     4     2     0x00     ·    PAD
19          19      0      19     4     3     0x00     ·    PAD
20          20      0      20     5     0     0x00     ·    PAD
21          21      0      21     5     1     0x00     ·    PAD
22          22      0      22     5     2     0x00     ·    PAD
23          23      0      23     5     3     0x00     ·    PAD
24          24      0      24     6     0     0x00     ·    PAD
25          25      0      25     6     1     0x00     ·    PAD
26          26      0      26     6     2     0x00     ·    PAD
27          27      0      27     6     3     0x00     ·    PAD
28          28      0      28     7     0     0x00     ·    PAD
29          29      0      29     7     1     0x00     ·    PAD
30          30      0      30     7     2     0x00     ·    PAD
31          31      0      31     7     3     0x00     ·    PAD

### Block 0 input words W0..W15

    block  word           W        bytes ascii  transitions  bitcount
0       0     0  0x61626380  61 62 63 80  abc·            3        11
1       0     1  0x00000000  00 00 00 00  ····            0         0
2       0     2  0x00000000  00 00 00 00  ····            0         0
3       0     3  0x00000000  00 00 00 00  ····            0         0
4       0     4  0x00000000  00 00 00 00  ····            0         0
5       0     5  0x00000000  00 00 00 00  ····            0         0
6       0     6  0x00000000  00 00 00 00  ····            0         0
7       0     7  0x00000000  00 00 00 00  ····            0         0
8       0     8  0x00000000  00 00 00 00  ····            0         0
9       0     9  0x00000000  00 00 00 00  ····            0         0
10      0    10  0x00000000  00 00 00 00  ····            0         0
11      0    11  0x00000000  00 00 00 00  ····            0         0
12      0    12  0x00000000  00 00 00 00  ····            0         0
13      0    13  0x00000000  00 00 00 00  ····            0         0
14      0    14  0x00000000  00 00 00 00  ····            0         0
15      0    15  0x00000018  00 00 00 18  ····            1         2

### Block 0 schedule W0..W63

    block   t           W  bitcount  ... src_t-16 src_t-15  src_t-7  src_t-2
0       0   0  0x61626380        11  ...      NaN      NaN      NaN      NaN
1       0   1  0x00000000         0  ...      NaN      NaN      NaN      NaN
2       0   2  0x00000000         0  ...      NaN      NaN      NaN      NaN
3       0   3  0x00000000         0  ...      NaN      NaN      NaN      NaN
4       0   4  0x00000000         0  ...      NaN      NaN      NaN      NaN
5       0   5  0x00000000         0  ...      NaN      NaN      NaN      NaN
6       0   6  0x00000000         0  ...      NaN      NaN      NaN      NaN
7       0   7  0x00000000         0  ...      NaN      NaN      NaN      NaN
8       0   8  0x00000000         0  ...      NaN      NaN      NaN      NaN
9       0   9  0x00000000         0  ...      NaN      NaN      NaN      NaN
10      0  10  0x00000000         0  ...      NaN      NaN      NaN      NaN
11      0  11  0x00000000         0  ...      NaN      NaN      NaN      NaN
12      0  12  0x00000000         0  ...      NaN      NaN      NaN      NaN
13      0  13  0x00000000         0  ...      NaN      NaN      NaN      NaN
14      0  14  0x00000000         0  ...      NaN      NaN      NaN      NaN
15      0  15  0x00000018         2  ...      NaN      NaN      NaN      NaN
16      0  16  0x61626380        11  ...      0.0      1.0      9.0     14.0
17      0  17  0x000f0000         4  ...      1.0      2.0     10.0     15.0
18      0  18  0x7da86405        14  ...      2.0      3.0     11.0     16.0
19      0  19  0x600003c6         8  ...      3.0      4.0     12.0     17.0

[20 rows x 10 columns]

### Block 0 rounds

    block  round          Wt  ... shape_lock T1_carry_bits T2_carry_bits
0       0      0  0x61626380  ...       True            22            10
1       0      1  0x00000000  ...       True            18            11
2       0      2  0x00000000  ...       True            17             6
3       0      3  0x00000000  ...       True            18             3
4       0      4  0x00000000  ...       True            21             5
5       0      5  0x00000000  ...       True            16             5
6       0      6  0x00000000  ...       True            17             5
7       0      7  0x00000000  ...       True            17             8
8       0      8  0x00000000  ...       True            18             6
9       0      9  0x00000000  ...       True            16             7
10      0     10  0x00000000  ...       True            21             7
11      0     11  0x00000000  ...       True            20             6
12      0     12  0x00000000  ...       True            22            13
13      0     13  0x00000000  ...       True            18             6
14      0     14  0x00000000  ...       True            22             7
15      0     15  0x00000018  ...       True            19            12

[16 rows x 16 columns]

### Block 0 feed-forward

   block  lane        H_in internal_out       H_out
0      0     0  0x6a09e667   0x506e3058  0xba7816bf
1      0     1  0xbb67ae85   0xd39a2165  0x8f01cfea
2      0     2  0x3c6ef372   0x04d24d6c  0x414140de
3      0     3  0xa54ff53a   0xb85e2ce9  0x5dae2223
4      0     4  0x510e527f   0x5ef50f24  0xb00361a3
5      0     5  0x9b05688c   0xfb121210  0x96177a9c
6      0     6  0x1f83d9ab   0x948d25b6  0xb410ff61
7      0     7  0x5be0cd19   0x961f4894  0xf20015ad

## GlassKey Viewer Alpha — GlassKey

         field                                              value
0  message_len                                                  8
1   padded_len                                                 64
2       blocks                                                  1
3       rounds                                                 64
4       digest  b31ca983c973a72332be2e88cc4d75ea327ab8e7fdaadb...

### Byte stream

    byte_index  block  offset  word  lane byte_hex ascii source
0            0      0       0     0     0     0x47     G    MSG
1            1      0       1     0     1     0x6c     l    MSG
2            2      0       2     0     2     0x61     a    MSG
3            3      0       3     0     3     0x73     s    MSG
4            4      0       4     1     0     0x73     s    MSG
5            5      0       5     1     1     0x4b     K    MSG
6            6      0       6     1     2     0x65     e    MSG
7            7      0       7     1     3     0x79     y    MSG
8            8      0       8     2     0     0x80     ·  PAD80
9            9      0       9     2     1     0x00     ·    PAD
10          10      0      10     2     2     0x00     ·    PAD
11          11      0      11     2     3     0x00     ·    PAD
12          12      0      12     3     0     0x00     ·    PAD
13          13      0      13     3     1     0x00     ·    PAD
14          14      0      14     3     2     0x00     ·    PAD
15          15      0      15     3     3     0x00     ·    PAD
16          16      0      16     4     0     0x00     ·    PAD
17          17      0      17     4     1     0x00     ·    PAD
18          18      0      18     4     2     0x00     ·    PAD
19          19      0      19     4     3     0x00     ·    PAD
20          20      0      20     5     0     0x00     ·    PAD
21          21      0      21     5     1     0x00     ·    PAD
22          22      0      22     5     2     0x00     ·    PAD
23          23      0      23     5     3     0x00     ·    PAD
24          24      0      24     6     0     0x00     ·    PAD
25          25      0      25     6     1     0x00     ·    PAD
26          26      0      26     6     2     0x00     ·    PAD
27          27      0      27     6     3     0x00     ·    PAD
28          28      0      28     7     0     0x00     ·    PAD
29          29      0      29     7     1     0x00     ·    PAD
30          30      0      30     7     2     0x00     ·    PAD
31          31      0      31     7     3     0x00     ·    PAD

### Block 0 input words W0..W15

    block  word           W        bytes ascii  transitions  bitcount
0       0     0  0x476c6173  47 6c 61 73  Glas            3        16
1       0     1  0x734b6579  73 4b 65 79  sKey            3        18
2       0     2  0x80000000  80 00 00 00  ····            1         1
3       0     3  0x00000000  00 00 00 00  ····            0         0
4       0     4  0x00000000  00 00 00 00  ····            0         0
5       0     5  0x00000000  00 00 00 00  ····            0         0
6       0     6  0x00000000  00 00 00 00  ····            0         0
7       0     7  0x00000000  00 00 00 00  ····            0         0
8       0     8  0x00000000  00 00 00 00  ····            0         0
9       0     9  0x00000000  00 00 00 00  ····            0         0
10      0    10  0x00000000  00 00 00 00  ····            0         0
11      0    11  0x00000000  00 00 00 00  ····            0         0
12      0    12  0x00000000  00 00 00 00  ····            0         0
13      0    13  0x00000000  00 00 00 00  ····            0         0
14      0    14  0x00000000  00 00 00 00  ····            0         0
15      0    15  0x00000040  00 00 00 40  ···@            1         1

### Block 0 schedule W0..W63

    block   t           W  bitcount  ... src_t-16 src_t-15  src_t-7  src_t-2
0       0   0  0x476c6173        16  ...      NaN      NaN      NaN      NaN
1       0   1  0x734b6579        18  ...      NaN      NaN      NaN      NaN
2       0   2  0x80000000         1  ...      NaN      NaN      NaN      NaN
3       0   3  0x00000000         0  ...      NaN      NaN      NaN      NaN
4       0   4  0x00000000         0  ...      NaN      NaN      NaN      NaN
5       0   5  0x00000000         0  ...      NaN      NaN      NaN      NaN
6       0   6  0x00000000         0  ...      NaN      NaN      NaN      NaN
7       0   7  0x00000000         0  ...      NaN      NaN      NaN      NaN
8       0   8  0x00000000         0  ...      NaN      NaN      NaN      NaN
9       0   9  0x00000000         0  ...      NaN      NaN      NaN      NaN
10      0  10  0x00000000         0  ...      NaN      NaN      NaN      NaN
11      0  11  0x00000000         0  ...      NaN      NaN      NaN      NaN
12      0  12  0x00000000         0  ...      NaN      NaN      NaN      NaN
13      0  13  0x00000000         0  ...      NaN      NaN      NaN      NaN
14      0  14  0x00000000         0  ...      NaN      NaN      NaN      NaN
15      0  15  0x00000040         1  ...      NaN      NaN      NaN      NaN
16      0  16  0x6d3e082a        14  ...      0.0      1.0      9.0     14.0
17      0  17  0x84738579        15  ...      1.0      2.0     10.0     15.0
18      0  18  0x450b34ba        14  ...      2.0      3.0     11.0     16.0
19      0  19  0xb232ee56        17  ...      3.0      4.0     12.0     17.0

[20 rows x 10 columns]

### Block 0 rounds

    block  round          Wt  ... shape_lock T1_carry_bits T2_carry_bits
0       0      0  0x476c6173  ...       True            23            10
1       0      1  0x734b6579  ...       True            25             7
2       0      2  0x80000000  ...       True            21             5
3       0      3  0x00000000  ...       True            20             5
4       0      4  0x00000000  ...       True            18             9
5       0      5  0x00000000  ...       True            20             4
6       0      6  0x00000000  ...       True            20             6
7       0      7  0x00000000  ...       True            21             8
8       0      8  0x00000000  ...       True            16             3
9       0      9  0x00000000  ...       True            16            10
10      0     10  0x00000000  ...       True            19            11
11      0     11  0x00000000  ...       True            18             5
12      0     12  0x00000000  ...       True            18             4
13      0     13  0x00000000  ...       True            16             6
14      0     14  0x00000000  ...       True            21             9
15      0     15  0x00000040  ...       True            20            10

[16 rows x 16 columns]

### Block 0 feed-forward

   block  lane        H_in internal_out       H_out
0      0     0  0x6a09e667   0x4912c31c  0xb31ca983
1      0     1  0xbb67ae85   0x0e0bf89e  0xc973a723
2      0     2  0x3c6ef372   0xf64f3b16  0x32be2e88
3      0     3  0xa54ff53a   0x26fd80b0  0xcc4d75ea
4      0     4  0x510e527f   0xe16c6668  0x327ab8e7
5      0     5  0x9b05688c   0x62a572e9  0xfdaadb75
6      0     6  0x1f83d9ab   0xd98a4cca  0xf90e2675
7      0     7  0x5be0cd19   0x8040e785  0xdc21b49e

Custom calls:
  trace = sha256_forward_trace(b'abc')
  df_bytes(trace)
  df_words(trace, 0)
  df_schedule(trace, 0, expanded=True)
  df_rounds(trace, 0)
  df_feedforward(trace)
  df_schedule_weave(trace, 0)
  df_channel_weave(trace, 0, 'post_a')

In [3]:
gk.df_schedule_weave(trace_gk, 0).head(12)

     i left_label right_label  ... delta_bits sigma_bits            budget_int
0    0         W0          W1  ...         14         20  10354970295692827060
1    1         W1          W2  ...         14         19  16706567630470604386
2    2         W2          W3  ...          1          1   9223372036854775808
3    3         W3          W4  ...          0          0                     0
4    4         W4          W5  ...          0          0                     0
5    5         W5          W6  ...          0          0                     0
6    6         W6          W7  ...          0          0                     0
7    7         W7          W8  ...          0          0                     0
8    8         W8          W9  ...          0          0                     0
9    9         W9         W10  ...          0          0                     0
10  10        W10         W11  ...          0          0                     0
11  11        W11         W12  ...          0          0                     0

[12 rows x 10 columns]

In [4]:
gk.df_channel_weave(trace_gk, 0, 'post_a').head(12)

     i left_label right_label  ... delta_bits sigma_bits            budget_int
0    0         r0          r1  ...         20         17  17770099941546271202
1    1         r1          r2  ...         15         19  14965247388697269460
2    2         r2          r3  ...         14         17  13070012068416837690
3    3         r3          r4  ...         19         18  16240193771624358344
4    4         r4          r5  ...         20         15  19757842970710860448
5    5         r5          r6  ...         14         19  11414483630261168498
6    6         r6          r7  ...         20         19  24504232804283826842
7    7         r7          r8  ...         15         17  18733476890465202280
8    8         r8          r9  ...         16         12  15893810515820088360
9    9         r9         r10  ...         16         15  15682275932711136040
10  10        r10         r11  ...         14         17  11132987526523787234
11  11        r11         r12  ...         22         17  21892370602650237666

[12 rows x 10 columns]

In [5]:
# Custom examples
# ascii_trace = gk.sha256_forward_trace(gk.msg_ascii_0_127())
# digits_trace = gk.sha256_forward_trace(gk.msg_digits(1024))
# gk.df_feedforward(ascii_trace)
# gk.df_rounds(digits_trace, 0).head(20)